[project]
name = "code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bleak>=2.0.0",
    "flask>=3.0.0",
    "flask-cors>=4.0.0",
    "aiohttp>=3.9.0",
]
